"""
Python bindings for the C++ limit order book engine
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AckEvent', 'BASIS_POINTS_PER_UNIT', 'BookLevel', 'BookSnapshot', 'CancelEvent', 'CancelReason', 'FIFOMatcher', 'FillEvent', 'HistoricalReplayer', 'HistoricalReplayerConfig', 'MatchingAlgorithm', 'Order', 'OrderBookCallbacks', 'OrderBookInterface', 'OrderSource', 'OrderStatus', 'OrderType', 'ReplaySpeed', 'Side', 'SimulationConfig', 'SimulationEngine', 'TreeOrderBook', 'TriggerEvent', 'format_price', 'from_basis_points', 'opposite', 'tick_ceil', 'tick_floor', 'to_basis_points']
class AckEvent:
    @property
    def message(self) -> str:
        ...
    @property
    def order_id(self) -> int:
        ...
    @property
    def status(self) -> OrderStatus:
        ...
    @property
    def symbol(self) -> str:
        ...
    @property
    def timestamp(self) -> int:
        ...
class BookLevel:
    @property
    def order_count(self) -> int:
        ...
    @property
    def price(self) -> int:
        ...
    @property
    def quantity(self) -> int:
        ...
class BookSnapshot:
    @property
    def asks(self) -> list[BookLevel]:
        ...
    @property
    def bids(self) -> list[BookLevel]:
        ...
    @property
    def last_trade_price(self) -> int:
        ...
    @property
    def sequence(self) -> int:
        ...
    @property
    def symbol(self) -> str:
        ...
    @property
    def timestamp(self) -> int:
        ...
class CancelEvent:
    @property
    def order_id(self) -> int:
        ...
    @property
    def price(self) -> int:
        ...
    @property
    def reason(self) -> CancelReason:
        ...
    @property
    def remaining_quantity(self) -> int:
        ...
    @property
    def sequence(self) -> int:
        ...
    @property
    def side(self) -> Side:
        ...
    @property
    def symbol(self) -> str:
        ...
    @property
    def timestamp(self) -> int:
        ...
class CancelReason:
    """
    Members:
    
      CLIENT_REQUEST
    
      IOC_EXPIRED
    
      FOK_FAILED
    
      MARKET_NO_LIQUIDITY
    
      RISK_REJECTED
    
      STOP_CANCELLED
    
      SELF_TRADE
    """
    CLIENT_REQUEST: typing.ClassVar[CancelReason]  # value = <CancelReason.CLIENT_REQUEST: 0>
    FOK_FAILED: typing.ClassVar[CancelReason]  # value = <CancelReason.FOK_FAILED: 2>
    IOC_EXPIRED: typing.ClassVar[CancelReason]  # value = <CancelReason.IOC_EXPIRED: 1>
    MARKET_NO_LIQUIDITY: typing.ClassVar[CancelReason]  # value = <CancelReason.MARKET_NO_LIQUIDITY: 3>
    RISK_REJECTED: typing.ClassVar[CancelReason]  # value = <CancelReason.RISK_REJECTED: 4>
    SELF_TRADE: typing.ClassVar[CancelReason]  # value = <CancelReason.SELF_TRADE: 6>
    STOP_CANCELLED: typing.ClassVar[CancelReason]  # value = <CancelReason.STOP_CANCELLED: 5>
    __members__: typing.ClassVar[dict[str, CancelReason]]  # value = {'CLIENT_REQUEST': <CancelReason.CLIENT_REQUEST: 0>, 'IOC_EXPIRED': <CancelReason.IOC_EXPIRED: 1>, 'FOK_FAILED': <CancelReason.FOK_FAILED: 2>, 'MARKET_NO_LIQUIDITY': <CancelReason.MARKET_NO_LIQUIDITY: 3>, 'RISK_REJECTED': <CancelReason.RISK_REJECTED: 4>, 'STOP_CANCELLED': <CancelReason.STOP_CANCELLED: 5>, 'SELF_TRADE': <CancelReason.SELF_TRADE: 6>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class FIFOMatcher(MatchingAlgorithm):
    def __init__(self) -> None:
        ...
    def name(self) -> str:
        ...
class FillEvent:
    @property
    def aggressive_order_id(self) -> int:
        ...
    @property
    def aggressor_side(self) -> Side:
        ...
    @property
    def fill_price(self) -> int:
        ...
    @property
    def fill_quantity(self) -> int:
        ...
    @property
    def passive_order_id(self) -> int:
        ...
    @property
    def sequence(self) -> int:
        ...
    @property
    def symbol(self) -> str:
        ...
    @property
    def timestamp(self) -> int:
        ...
class HistoricalReplayer(OrderSource):
    def __init__(self, config: HistoricalReplayerConfig) -> None:
        ...
    def bytes_read(self) -> int:
        ...
    def exhausted(self) -> bool:
        ...
    def messages_parsed(self) -> int:
        ...
    def name(self) -> str:
        ...
    def orders_replayed(self) -> int:
        ...
    def orders_skipped(self) -> int:
        ...
class HistoricalReplayerConfig:
    path: str
    speed: ReplaySpeed
    symbol_filter: str
    verbose: bool
    def __init__(self) -> None:
        ...
    @property
    def end_time(self) -> int:
        ...
    @end_time.setter
    def end_time(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def fixed_ns(self) -> int:
        ...
    @fixed_ns.setter
    def fixed_ns(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def start_time(self) -> int:
        ...
    @start_time.setter
    def start_time(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class MatchingAlgorithm:
    pass
class Order:
    side: Side
    status: OrderStatus
    symbol: str
    type: OrderType
    def __init__(self, id: typing.SupportsInt | typing.SupportsIndex, symbol: str, side: Side, type: OrderType, price: typing.SupportsInt | typing.SupportsIndex, quantity: typing.SupportsInt | typing.SupportsIndex, timestamp: typing.SupportsInt | typing.SupportsIndex = 0, limit_price: typing.SupportsInt | typing.SupportsIndex = 0, status: OrderStatus = ...) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def id(self) -> int:
        ...
    @id.setter
    def id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def limit_price(self) -> int:
        ...
    @limit_price.setter
    def limit_price(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def orig_quantity(self) -> int:
        ...
    @orig_quantity.setter
    def orig_quantity(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def price(self) -> int:
        ...
    @price.setter
    def price(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def quantity_remaining(self) -> int:
        ...
    @quantity_remaining.setter
    def quantity_remaining(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def timestamp(self) -> int:
        ...
    @timestamp.setter
    def timestamp(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class OrderBookCallbacks:
    on_ack: collections.abc.Callable[[AckEvent], None]
    on_book_update: collections.abc.Callable[[BookSnapshot], None]
    on_cancel: collections.abc.Callable[[CancelEvent], None]
    on_fill: collections.abc.Callable[[FillEvent], None]
    def __init__(self) -> None:
        ...
class OrderBookInterface:
    pass
class OrderSource:
    pass
class OrderStatus:
    """
    Members:
    
      NEW
    
      PENDING_TRIGGER
    
      PARTIALLY_FILLED
    
      FILLED
    
      CANCELLED
    
      REJECTED
    """
    CANCELLED: typing.ClassVar[OrderStatus]  # value = <OrderStatus.CANCELLED: 4>
    FILLED: typing.ClassVar[OrderStatus]  # value = <OrderStatus.FILLED: 3>
    NEW: typing.ClassVar[OrderStatus]  # value = <OrderStatus.NEW: 0>
    PARTIALLY_FILLED: typing.ClassVar[OrderStatus]  # value = <OrderStatus.PARTIALLY_FILLED: 2>
    PENDING_TRIGGER: typing.ClassVar[OrderStatus]  # value = <OrderStatus.PENDING_TRIGGER: 1>
    REJECTED: typing.ClassVar[OrderStatus]  # value = <OrderStatus.REJECTED: 5>
    __members__: typing.ClassVar[dict[str, OrderStatus]]  # value = {'NEW': <OrderStatus.NEW: 0>, 'PENDING_TRIGGER': <OrderStatus.PENDING_TRIGGER: 1>, 'PARTIALLY_FILLED': <OrderStatus.PARTIALLY_FILLED: 2>, 'FILLED': <OrderStatus.FILLED: 3>, 'CANCELLED': <OrderStatus.CANCELLED: 4>, 'REJECTED': <OrderStatus.REJECTED: 5>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class OrderType:
    """
    Members:
    
      LIMIT
    
      MARKET
    
      MARKET_LIMIT
    
      STOP
    
      STOP_LIMIT
    
      IMMEDIATE_OR_CANCEL
    
      FILL_OR_KILL
    """
    FILL_OR_KILL: typing.ClassVar[OrderType]  # value = <OrderType.FILL_OR_KILL: 6>
    IMMEDIATE_OR_CANCEL: typing.ClassVar[OrderType]  # value = <OrderType.IMMEDIATE_OR_CANCEL: 5>
    LIMIT: typing.ClassVar[OrderType]  # value = <OrderType.LIMIT: 0>
    MARKET: typing.ClassVar[OrderType]  # value = <OrderType.MARKET: 1>
    MARKET_LIMIT: typing.ClassVar[OrderType]  # value = <OrderType.MARKET_LIMIT: 2>
    STOP: typing.ClassVar[OrderType]  # value = <OrderType.STOP: 3>
    STOP_LIMIT: typing.ClassVar[OrderType]  # value = <OrderType.STOP_LIMIT: 4>
    __members__: typing.ClassVar[dict[str, OrderType]]  # value = {'LIMIT': <OrderType.LIMIT: 0>, 'MARKET': <OrderType.MARKET: 1>, 'MARKET_LIMIT': <OrderType.MARKET_LIMIT: 2>, 'STOP': <OrderType.STOP: 3>, 'STOP_LIMIT': <OrderType.STOP_LIMIT: 4>, 'IMMEDIATE_OR_CANCEL': <OrderType.IMMEDIATE_OR_CANCEL: 5>, 'FILL_OR_KILL': <OrderType.FILL_OR_KILL: 6>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ReplaySpeed:
    """
    Members:
    
      FAST
    
      REALTIME
    
      FIXED_NS
    """
    FAST: typing.ClassVar[ReplaySpeed]  # value = <ReplaySpeed.FAST: 0>
    FIXED_NS: typing.ClassVar[ReplaySpeed]  # value = <ReplaySpeed.FIXED_NS: 2>
    REALTIME: typing.ClassVar[ReplaySpeed]  # value = <ReplaySpeed.REALTIME: 1>
    __members__: typing.ClassVar[dict[str, ReplaySpeed]]  # value = {'FAST': <ReplaySpeed.FAST: 0>, 'REALTIME': <ReplaySpeed.REALTIME: 1>, 'FIXED_NS': <ReplaySpeed.FIXED_NS: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Side:
    """
    Members:
    
      BID
    
      ASK
    """
    ASK: typing.ClassVar[Side]  # value = <Side.ASK: 1>
    BID: typing.ClassVar[Side]  # value = <Side.BID: 0>
    __members__: typing.ClassVar[dict[str, Side]]  # value = {'BID': <Side.BID: 0>, 'ASK': <Side.ASK: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SimulationConfig:
    emit_on_every_order: bool
    symbol: str
    verbose: bool
    def __init__(self) -> None:
        ...
    @property
    def end_time(self) -> int:
        ...
    @end_time.setter
    def end_time(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def order_id_start(self) -> int:
        ...
    @order_id_start.setter
    def order_id_start(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def snapshot_depth(self) -> int:
        ...
    @snapshot_depth.setter
    def snapshot_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def start_time(self) -> int:
        ...
    @start_time.setter
    def start_time(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def yield_every_n_orders(self) -> int:
        ...
    @yield_every_n_orders.setter
    def yield_every_n_orders(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class SimulationEngine:
    def __init__(self, config: SimulationConfig, book: OrderBookInterface) -> None:
        ...
    def add_source(self, source: OrderSource) -> None:
        ...
    def book(self) -> OrderBookInterface:
        ...
    def config(self) -> SimulationConfig:
        ...
    def current_time(self) -> int:
        ...
    def historical_replayer(self) -> HistoricalReplayer:
        ...
    def is_running(self) -> bool:
        ...
    def orders_processed(self) -> int:
        ...
    def orders_rejected(self) -> int:
        ...
    def reset(self) -> None:
        ...
    def run(self) -> None:
        ...
    def set_ack_callback(self, callback: collections.abc.Callable[[AckEvent], None]) -> None:
        ...
    def set_cancel_callback(self, callback: collections.abc.Callable[[CancelEvent], None]) -> None:
        ...
    def set_fill_callback(self, callback: collections.abc.Callable[[FillEvent], None]) -> None:
        ...
    def set_snapshot_callback(self, callback: collections.abc.Callable[[BookSnapshot], None]) -> None:
        ...
    def set_tick_callback(self, callback: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, BookSnapshot], None]) -> None:
        ...
    def set_trigger_callback(self, callback: collections.abc.Callable[[TriggerEvent], None]) -> None:
        ...
    def stop(self) -> None:
        ...
    def stops_triggered(self) -> int:
        ...
    def tick_count(self) -> int:
        ...
class TreeOrderBook(OrderBookInterface):
    def __init__(self, symbol: str, matcher: MatchingAlgorithm, callbacks: OrderBookCallbacks = ...) -> None:
        ...
    def add(self, order: Order) -> None:
        ...
    def ask_depth(self) -> int:
        ...
    def best_ask(self) -> int | None:
        ...
    def best_bid(self) -> int | None:
        ...
    def bid_depth(self) -> int:
        ...
    def cancel(self, order_id: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def execute(self, order_id: typing.SupportsInt | typing.SupportsIndex, quantity: typing.SupportsInt | typing.SupportsIndex, timestamp: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def has_order(self, order_id: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def last_trade_price(self) -> int:
        ...
    def mid_price(self) -> float | None:
        ...
    def reduce(self, order_id: typing.SupportsInt | typing.SupportsIndex, quantity: typing.SupportsInt | typing.SupportsIndex, timestamp: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def replace(self, old_order_id: typing.SupportsInt | typing.SupportsIndex, new_order: Order) -> None:
        ...
    def sequence(self) -> int:
        ...
    def set_callbacks(self, callbacks: OrderBookCallbacks) -> None:
        ...
    def set_matching_algorithm(self, algo: MatchingAlgorithm) -> None:
        ...
    def snapshot(self, depth: typing.SupportsInt | typing.SupportsIndex = 10) -> BookSnapshot:
        ...
    def spread(self) -> int | None:
        ...
    def symbol(self) -> str:
        ...
    def total_ask_qty(self) -> int:
        ...
    def total_bid_qty(self) -> int:
        ...
    def weighted_mid(self) -> float | None:
        ...
class TriggerEvent:
    @property
    def converted_to(self) -> OrderType:
        ...
    @property
    def side(self) -> Side:
        ...
    @property
    def stop_order_id(self) -> int:
        ...
    @property
    def stop_price(self) -> int:
        ...
    @property
    def symbol(self) -> str:
        ...
    @property
    def timestamp(self) -> int:
        ...
    @property
    def trigger_trade_price(self) -> int:
        ...
    @property
    def triggered_order_id(self) -> int:
        ...
def format_price(basis_points: typing.SupportsInt | typing.SupportsIndex) -> str:
    """
    Format a basis-point price as a human-readable string.
    """
def from_basis_points(basis_points: typing.SupportsInt | typing.SupportsIndex) -> float:
    """
    Convert basis points back to a double price.
    """
def opposite(side: Side) -> Side:
    """
    Return the opposite side (BID <-> ASK).
    """
def tick_ceil(price: typing.SupportsInt | typing.SupportsIndex, tick_size: typing.SupportsInt | typing.SupportsIndex) -> int:
    ...
def tick_floor(price: typing.SupportsInt | typing.SupportsIndex, tick_size: typing.SupportsInt | typing.SupportsIndex) -> int:
    ...
def to_basis_points(price: typing.SupportsFloat | typing.SupportsIndex) -> int:
    """
    Convert a double price to basis points (int64), rounded.
    """
BASIS_POINTS_PER_UNIT: int = 10000
